FROM python:3.8

LABEL maintainer="li.xin.ze@163.com"

# WORKDIR /app
#
# COPY . .





# RUN apt-get update && apt-get install -y python3.7

# EXPOSE 5000

CMD ["echo", "hello world...! from my first docker image"]
  
