import argparse

parser = argparse.ArgumentParser(description="train")
parser.add_argument("--train_path", type=str, default="./data/train-sample.txt", help="train file")
parser.add_argument("--test_path", type=str, default="./data/test.txt", help="test file")
parser.add_argument("--output_dir", type=str, default="checkpoints/", help="output_dir")
parser.add_argument("--vocab_file", type=str, default="./data/vocab.txt", help="vocab_file")
parser.add_argument("--tag_file", type=str, default="./data/tags.txt", help="tag_file")
parser.add_argument("--batch_size", type=int, default=1, help="batch_size")
parser.add_argument("--hidden_num", type=int, default=512, help="hidden_num")
parser.add_argument("--max_token_len", type=int, default=512, help="max_token_len")
parser.add_argument("--embedding_size", type=int, default=300, help="embedding_size")
parser.add_argument("--embedding_file", type=str, default=None, help="embedding_file")
parser.add_argument("--epoch", type=int, default=20, help="epoch")
parser.add_argument("--lr", type=float, default=1e-3, help="lr")
parser.add_argument("--lstm_layer", type=str, default='gru', help="lstm_layer")
parser.add_argument("--crf_layer", type=bool, default=True, help="crf_layer")
args = parser.parse_args()
